version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
# volumes:
#   hapi-fhir-mysql:

  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: hapi
      POSTGRES_DB: fhir
    ports: 
      - 5000:5432
    volumes: 
      - fhirData:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
    links:
      - db
      
volumes:
  fhirData:
